apiVersion: v1
kind: Pod
metadata: 
  name: kube-controller
spec: 
  hostNetwork: true
  volumes:
    - name: "etc-kubernetes"
      hostPath:
        path: "/etc/kubernetes"
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "var-run-kubernetes"
      hostPath:
        path: "/var/run/kubernetes"
    - name: "etcd-datadir"
      hostPath:
        path: "/var/lib/etcd"
    - name: "usr"
      hostPath:
        path: "/usr"
    - name: "lib64"
      hostPath:
        path: "/lib64"
  containers:
    - name: "kube-apiserver"
      image: "b.gcr.io/kuar/kube-apiserver:1.0.3"
      args: 
        - "--allow-privileged=true"
        - "--etcd-servers=http://127.0.0.1:4001"
        - "--insecure-bind-address=0.0.0.0"
        - "--service-cluster-ip-range=10.100.0.0/24"
        - "-logtostderr=true"
        - "--v=5"
      volumeMounts:
        - mountPath: /etc/kubernetes
          name: "etc-kubernetes"
        - mountPath: /var/run/kubernetes
          name: "var-run-kubernetes"
    - name: "kube-controller-manager"
      image: "b.gcr.io/kuar/kube-controller-manager:1.0.3"
      args: 
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "kube-scheduler"
      image: "b.gcr.io/kuar/kube-scheduler:1.0.3"
      args:
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "kube-proxy"
      image: "b.gcr.io/kuar/kube-proxy:1.0.3"
      args:
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /etc/kubernetes
          name: "etc-kubernetes"
        - mountPath: /etc/ssl/certs
          name: "ssl-certs"
        - mountPath: /usr
          name: "usr"
        - mountPath: /lib64
          name: "lib64"
